### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by fjullien** [nmoroze/tclint#34]
Hi,

I tried tclint on the openocd source code (lot of tcl files). I got this:

```
src/helper/startup.tcl:12:24: syntax error: reached EOF without finding end of command substitution
Traceback (most recent call last):
  File "/home/franck/.local/bin//tclint", line 8, in <module>
    sys.exit(main())
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/tclint.py", line 229, in main
    violations = lint(script, config.get_for_path(path), path, debug=args.debug)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/tclint.py", line 132, in lint
    tree = parser.parse(script)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 119, in parse
    tree = self._parse_script(lexer)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 212, in _parse_script
    cmd = self.parse_command(ts)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 279, in parse_command
    parsed_args = self._parse_command_args(routine.contents, args)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 154, in _parse_command_args
    new_args = func(args, self)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/commands/builtin.py", line 326, in _proc
    return args[0:2] + [parser.parse_script(args[2])]
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 182, in parse_script
    script = self.parse(node.contents, pos=node.contents_pos)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 119, in parse
    tree = self._parse_script(lexer)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 212, in _parse_script
    cmd = self.parse_command(ts)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 279, in parse_command
    parsed_args = self._parse_command_args(routine.contents, args)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 154, in _parse_command_args
    new_args = func(args, self)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/commands/builtin.py", line 420, in _switch
    parsed_patterns_and_commands.append(parser.parse_script(node))
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 182, in parse_script
    script = self.parse(node.contents, pos=node.contents_pos)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 119, in parse
    tree = self._parse_script(lexer)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 212, in _parse_script
    cmd = self.parse_command(ts)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 279, in parse_command
    parsed_args = self._parse_command_args(routine.contents, args)
  File "/home/franck/.local/lib/python3.10/site-packages/tclint/parser.py", line 169, in _parse_command_args
    assert len(new_args) == len(args)
AssertionError

```
I hope it can help you improve your tool.

**Comment by nmoroze** [comment]
Thanks for filing this issue! I was able to reproduce this issue and have fixed it in commit https://github.com/nmoroze/tclint/commit/c33f7d02bf63c203553b88f6025813759ee2ed6c. 

This commit is in the latest release, v0.2.5. With the fix, tclint runs to completion on the openocd codebase. It also found some files with invalid Tcl syntax - I'll report these upstream.
